---
- name: setup and start redis container
  sudo: yes
  docker:
     name: redis
     image: redis
     command: redis-server /usr/local/etc/redis/redis.conf
     state: started
     volumes:
        - /shared_data/redis_configs:/usr/local/etc/redis:ro
        - /shared_data/redis_data:/data:rw

- name: setup and start navocat-collector container
  sudo: yes
  docker:
     name: navocat-collector
     image: medullan/navocat-collector
     pull: always
     state: started
     links:
       - "redis:collector-redis"
     ports:
        - "0.0.0.0:8000:8000"
     volumes:
        - /shared_data/meda_configs:/usr/src/app/meda_configs:ro
        - /shared_data/meda_configs/newrelic_config:/usr/src/app/config:ro
        - /shared_data/meda_data:/usr/src/app/meda_data:rw
        - /shared_data/log:/usr/src/app/log:rw 
     env:
        JRUBY_OPTS: -J-Xmx1g