---
- name: setup redis container
  sudo: yes
  docker:
     name: redis
     image: redis
     command: redis-server /usr/local/etc/redis/redis.conf
     state: started
     volumes:
        - /shared_data/redis_data:/data
        - /shared_data/meda_configs/redis.conf:/usr/local/etc/redis/redis.conf

- name: setup navocat-collector container
  sudo: yes
  docker:
     name: navocat-collector
     image: medullan/navocat-collector
     pull: always
     state: started
     links:
       - "redis:collector-redis"
     ports:
        - "0.0.0.0:8000:8000"
     volumes:
        - /shared_data/meda_configs:/usr/src/app/meda_configs
        - /shared_data/meda_data:/usr/src/app/meda_data
        - /shared_data/log:/usr/src/app/log
     env:
        JRUBY_OPTS: -J-Xmx1g